### ISSUE TITLE
The game in bluestack not starting

### ISSUE THREAD

**Issue by Panda123234** [PhoenixFire6879/Modern-Brawl#4]
Hi brawl stars won't run on bluestack because it asks for an update what can i do?

**Comment by KotoFickus** [comment]
look in the log, if there is no message "New connection! Ip: {your ip}", then the client does not connect to the server (used google translator)

**Comment by Panda123234** [comment]
i can connect to the server but the game needs an update

**Comment by PhoenixFire6934** [comment]
Emulators are not supported.
